In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
init_df = pd.read_excel('seasons.xlsx')

In [23]:
import pandas as pd

url = "https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2025-26/gws/merged_gw.csv"

online_df = pd.read_csv(url)

haaland2526 = online_df[online_df['name'] == 'Erling Haaland']

haaland2526 = haaland2526[['name','GW', 'total_points', 'bonus']]

haaland2526.head()

#tried using a github repository but i was not able to merge it correctly so i added the points naturally

                name  GW  total_points  bonus
157   Erling Haaland   1            13      3
851   Erling Haaland   2             2      0
1558  Erling Haaland   3             9      3
2277  Erling Haaland   4            13      3
3018  Erling Haaland   5             9      3

In [24]:
print(haaland2526)

                 name  GW  total_points  bonus
157    Erling Haaland   1            13      3
851    Erling Haaland   2             2      0
1558   Erling Haaland   3             9      3
2277   Erling Haaland   4            13      3
3018   Erling Haaland   5             9      3
3760   Erling Haaland   6            16      3
4503   Erling Haaland   7             8      2
5247   Erling Haaland   8            13      3
5993   Erling Haaland   9             2      0
6740   Erling Haaland  10            13      3
7487   Erling Haaland  11             4      0
8239   Erling Haaland  12             2      0
8994   Erling Haaland  13             2      0
9749   Erling Haaland  14            14      2
10507  Erling Haaland  15             2      0
11266  Erling Haaland  16            13      3
12033  Erling Haaland  17            16      3
12803  Erling Haaland  18             2      0
13580  Erling Haaland  19             2      0
14362  Erling Haaland  20             2      0
15153  Erling Haaland  21             6      0
15949  Erling Haaland  22             2      0
16750  Erling Haaland  23             1      0
17555  Erling Haaland  24             5      0
18369  Erling Haaland  25            11      3
19205  Erling Haaland  26             5      0
20082  Erling Haaland  27             6      1
20900  Erling Haaland  28             0      0
21719  Erling Haaland  29             2      0
22540  Erling Haaland  30             2      0
24029  Erling Haaland  32             2      0
24914  Erling Haaland  33             6      1
24915  Erling Haaland  33             7      1
26516  Erling Haaland  35             7      1
27371  Erling Haaland  36            11      2
27372  Erling Haaland  36             0      0
28273  Erling Haaland  37             9      3
29114  Erling Haaland  38             0      0

In [ ]:


# combined_df = pd.concat([init_df, haaland2324], ignore_index=True)
# combined_df.to_csv("merged_data.csv", index=False)

In [17]:
new_df = pd.read_csv("merged_data.csv")

In [18]:
new_df.head()

,SEASON,Date,Day,Round,Venue,Result,Squad,Opponent,Start,Pos,...,Crs,TklW,Int,OG,POINTS,Bonus,name,GW,total_points,bonus
0,2023-24,8/11/2023,Fri,Matchweek 1,Away,W,Manchester City,Burnley,Y,FW,...,0.0,0.0,0.0,0.0,13.0,3.0,NaN,NaN,NaN,NaN
1,2023-24,8/19/2023,Sat,Matchweek 2,Home,W,Manchester City,Newcastle,Y,FW,...,0.0,0.0,1.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN
2,2023-24,8/27/2023,Sun,Matchweek 3,Away,W,Manchester City,Sheffield United,Y,FW,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-24,9/2/2023,Sat,Matchweek 4,Home,W,Manchester City,Fulham,Y,FW,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-24,9/16/2023,Sat,Matchweek 5,Away,W,Manchester City,West Ham,Y,FW,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SEASON        114 non-null    str
 1   Date          114 non-null    str
 2   Day           114 non-null    str
 3   Round         114 non-null    str
 4   Venue         114 non-null    str
 5   Result        114 non-null    str
 6   Squad         114 non-null    str
 7   Opponent      114 non-null    str
 8   Start         114 non-null    str
 9   Pos           103 non-null    str
 10  Min           114 non-null    float64
 11  Gls           114 non-null    float64
 12  Ast           114 non-null    float64
 13  PK            114 non-null    float64
 14  PKatt         114 non-null    float64
 15  Sh            114 non-null    float64
 16  SoT           114 non-null    float64
 17  CrdY          114 non-null    float64
 18  CrdR          114 non-null    float64
 19  Fls           114 non-null    float64
 20  Fld           114 non-null    float64
 21  Off           113 non-null    float64
 22  Crs           114 non-null    float64
 23  TklW          114 non-null    float64
 24  Int           114 non-null    float64
 25  OG            114 non-null    float64
 26  POINTS        42 non-null     float64
 27  Bonus         2 non-null      float64
 28  name          38 non-null     str
 29  GW            38 non-null     float64
 30  total_points  38 non-null     float64
 31  bonus         38 non-null     float64
dtypes: float64(21), str(11)
memory usage: 38.1 KB